public class Main {
    public static void lanzaThrow() {
        try {
            new NullPointerException("Descripci贸n de la excepci贸n").fillInStackTrace();
        } catch (NullPointerException e) {
            System.out.println("Se captura por primera vez la excepci贸n.");
            throw e;
        }

    }
    public static void main(String[] args) {
        try {
            lanzaThrow();
        }catch(NullPointerException e){
            System.out.println("Se recaptura la excepci贸n: " + e);
        }
    }
}